services:
  registry-dev:
    image: registry:2
    container_name: registry-dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.passwd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry-dev:/data
      - ./auth:/auth
    # networks:
    #   - registry-dev

  # nginx-dev:
  #   image: nginx:alpine
  #   container_name: nginx-dev
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./nginx/ssl/:/etc/nginx/ssl/
  #   networks:
  #     - registry-dev

  portainer-dev:
    image: portainer/portainer-ce
    container_name: portainer-dev
    restart: always
    ports:
      # - "9000:9000"
      - 9443:9443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer-dev:/data
#     networks:
#       - registry-dev


# networks:
#   registry-dev:
#     driver: bridge



volumes:
  registry-dev:
  portainer-dev: